### ISSUE TITLE
Why not build upon Artifacts?

### ISSUE THREAD

**Issue by frankier** [chengchingwen/MyArtifacts.jl#6]
Thanks for the package. It really seems to fill a useful niche not covered by `Artifacts`.

The README says that the content addressable store is kept separate from the `Artifacts` content addressable store. Taking a cursory look at the source code, it does seem that `Artifacts` is not used internally.

I have a probably-not-anticipated need that I would like the following workflow that [I discuss more in-context in this issue on RDatasets.jl] (https://github.com/JuliaStats/RDatasets.jl/issues/141#issuecomment-1299986701). The idea is that a "data-repository package" can fetch stuff from a data repository for REPL development, and store tags in its own mutable `Artifacts.toml`. When a user is happy to have an artifact as a package/library dependency, they can import it into their own "static" `Artifacts.toml` and commit it so that users of their code are guaranteed to get the same version. If there were a common content addressable store, this process would be seemless and not trigger and additional download.

Is this a potentially supported use case of `OhMyArtifacts.jl`, or should I go ahead and build my own thing on top of `Artifacts` and `Scratch.jl`? Might you be able to share any insights into the trade-offs that led you to the current implementation?

**Comment by chengchingwen** [comment]
The main reason is that the storing policy is different. The smallest addressable unit that `Artifacts`stored is a folder and the identifier is the sha1 tree hash of that folder. OTOH, the smallest unit of `OhMyArtifacts` is a file and the identifier is the sha256 content hash of the file. So for `OhMyArtifacts`, we want to make sure that every single file is only stored exact one copy on the machine and thus we can't directly store the data in the same place. The origin of the design is to fulfill the need of [HuggingFaceApi.jl](https://github.com/FluxML/HuggingFaceApi.jl), where you don't want to download every files in a repository because it actually depends on the downstream usages. Therefore, folder based storage doesn't suit the need.

For the specific need, that seems to be a normal `Artifacts` workflow. You open an `Artifacts.toml`, run `create_artifact` to download the data to the store and generate the entry and then copy the entry to the `Artifacts.toml` of your package and commit the changes. You can automate the process a little by putting `Artifacts.toml` in scratchspace, but personally I don't think that would change much.

**Comment by frankier** [comment]
Okay! Thanks very much for the swift response. That makes a lot of sense that it was done for the needs of HuggingFace datasets. Thanks also for confirming that it seems that I may be able to get away with just `Artifacts` and `Scratch`.
